# Generated by Django 5.2.7 on 2025-10-01 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answers',
        ),
        migrations.RenameModel(
            old_name='EventReview',
            new_name='EventReviews',
        ),
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
    ]
