# Generated by Django 5.2.7 on 2025-10-01 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_answer_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreviews',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.events'),
        ),
    ]
